#! /bin/sh
CMDLINE="console=ttyHSL2,115200,n8 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3"
acp -fp arch/arm/boot/zImage kernel_image
mkbootimg --kernel kernel_image --ramdisk ../out/target/product/msm8960/ramdisk.img --cmdline "$CMDLINE"  --base 0x80200000 --pagesize 2048 --offset 0x02000000 --output boot.img
